<?= $this->extend('layouts/base') ?>

<?= $this->section('content') ?>
    <!--<h2>Dashboard</h2>-->
    
    <!--<div class="">-->
        <div class="py-2">
            <!--<div class="text-center mb-5">-->
            <!--    <h1 class="section-heading display-4 mb-3">Welcome user_name</h1>-->
                <!--<p class="text-muted lead"></p>-->
            <!--</div>-->
    
            <div class="row">
                <div class="col-md-3">
                    <div class="card feature-card h-100 p-4">
                        <div class="icon-wrapper bg-soft-primary text-primary">
                            <!--<svg width="24" height="24" fill="none" stroke="currentColor" stroke-width="2"-->
                            <!--    class="text-primary">-->
                            <!--    <path d="M12 2L2 7l10 5 10-5-10-5zM2 17l10 5 10-5M2 12l10 5 10-5" />-->
                            <!--</svg>-->
                            <strong class="counter-count" data-counter-duration="3000"><?= $parties ?></strong>
                        </div>
                        <h3 class="card-title">Parties</h3>
                        <p class="card-text text-muted">Total party count registered.</p>
                        <a href="<?= base_url('party'); ?>" class="btn btn-sm btn-outline-primary">View Listing</a>
                        <a href="<?= base_url('addOrUpdateParty'); ?>" class="btn btn-sm btn-outline-primary mt-2">Add Party</a>
                        <!--<button type="button" class="btn btn-sm btn-outline-primary" onclick="<?php // base_url('party') ?>">View listing</button>-->
                        <!--<button type="button" class="btn btn-sm btn-outline-primary mt-2" onclick="<?php // base_url('party') ?>">Add</button>-->
                    </div>
                </div>
    
                <div class="col-md-4">
                    <div class="card feature-card h-100 p-4">
                        <div class="icon-wrapper bg-soft-success text-success">
                            <!--<svg width="24" height="24" fill="none" stroke="currentColor" stroke-width="2"-->
                            <!--    class="text-success">-->
                            <!--    <path d="M22 12h-4l-3 9L9 3l-3 9H2" />-->
                            <!--</svg>-->
                            <strong class="counter-count" data-counter-duration="2000" id="party_transaction"><?= ($party_transactions  != null) ? $party_transactions : '0' ?></strong><b>&nbsp&nbsp₹</b>
                        </div>
                        <h3 class="card-title">Party Revenue</h3>
                        <p class="card-text text-muted" id="party-filtered-transaction"> Revenue generated by parties until now.</p>
                        <select class="form-select" name="party_id" id="party_list" onchange="party_change(this);">
                            <option value="0" selected>Select party</option>
                            <?php foreach($party_list as $key => $value) { ?>
                                <option value="<?= $key ?>"><?= $value ?></option>
                            <?php } ?>
                        </select>
                        <input class="form-select mt-2" type="text" name="party-daterange" id="party-transaction-daterange" value="" placeholder="Filter by date"/>
                    </div>
                </div>
    
                <div class="col-md-4">
                    <div class="card feature-card h-100 p-4">
                        <div class="icon-wrapper bg-soft-warning">
                            <!--<svg width="24" height="24" fill="none" stroke="currentColor" stroke-width="2"-->
                            <!--    class="text-warning">-->
                            <!--    <path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z" />-->
                            <!--</svg>-->
                            <strong class="counter-count" data-counter-duration="2000" id="ref_transaction"><?= ($ref_transactions  != null) ? $ref_transactions : '0' ?></strong><b>&nbsp&nbsp₹</b>
                        </div>
                        <h3 class="card-title">Refferal Revenue</h3>
                        <p class="card-text text-muted" id="ref-filtered-transaction">Revenue generated by refference until now.</p>
                        <select class="form-select" name="ref_id" id="ref_list" onchange="ref_change(this);">
                            <option value="0" selected>Select refferal party</option>
                            <?php foreach($ref_list as $key => $value) { ?>
                                <option value="<?= $key ?>"><?= $value ?></option>
                            <?php } ?>
                        </select>
                        <input class="form-select mt-2" type="text" name="ref-daterange" id="ref-transaction-daterange" value="" placeholder="Filter by date"/>
                    </div>
                </div>
            </div>
        </div>
    <!--</div>-->
    <div class="row">
        <!-- Main Content Area -->
        <div class="row g-3">
            <!-- Activity Timeline -->
            <div class="col-12 col-lg-12">
                <div class="card border-0 shadow-sm feature-card">
                    <div class="card-header bg-white border-0">
                        <div class="d-flex justify-content-between align-items-center">
                            <h5 class="mb-0">Recent Orders</h5>
                            <!--<button class="btn btn-link text-decoration-none p-0" onclick="console.lol(dmeo)">View All</button>-->
                            <a href="<?= base_url('order'); ?>" class="link-primary">View More</a>
                        </div>
                    </div>
                    <div class="card-body">
                            <table class="table table-striped">
                              <thead>
                                <tr>
                                  <th scope="col">#</th>
                                  <th scope="col">Order</th>
                                  <th scope="col">Party</th>
                                  <th scope="col">Total Amount</th>
                                </tr>
                              </thead>
                              <tbody>
                                <?php 
                                    $count = 0;
                                    foreach($latest_orders as $order){
                                        $count++;
                                        echo "
                                        <tr>
                                          <th scope='row'> $count </th>
                                          <td> ".$order['orders_name']." </td>
                                          <td> ".$order['party_name']." </td>
                                          <td> ".$order['total_price']." </td>
                                        </tr>";
                                } ?>
                                <!--<tr>-->
                                <!--  <th scope="row">2</th>-->
                                <!--  <td>Jacob</td>-->
                                <!--  <td>Thornton</td>-->
                                <!--  <td>@fat</td>-->
                                <!--</tr>-->
                                <!--<tr>-->
                                <!--  <th scope="row">3</th>-->
                                <!--  <td>Larry</td>-->
                                <!--  <td>the Bird</td>-->
                                <!--  <td>@twitter</td>-->
                                <!--</tr>-->
                              </tbody>
                            </table>
                    </div>
                </div>
            </div>
    </div>
    
<?= $this->endSection() ?>
<?= $this->section('js') ?>

<script>
    $(document).ready(function() {
        // console.log('hedgcfjs');
        
        //party transaction date range filter
        $('#party-transaction-daterange, input[name="party-daterange"]').daterangepicker({
            "startDate": "02/01/2025",
            "endDate": moment(),
            ranges: {
                'Today': [moment(), moment()],
                'Yesterday': [moment().subtract(1, 'days'), moment().subtract(1, 'days')],
                'Last 7 Days': [moment().subtract(6, 'days'), moment()],
                'Last 30 Days': [moment().subtract(29, 'days'), moment()],
                'This Month': [moment().startOf('month'), moment().endOf('month')],
                'Last Month': [moment().subtract(1, 'month').startOf('month'), moment().subtract(1, 'month').endOf('month')]
            },
            "linkedCalendars": false,
            "autoUpdateInput": true,
            "alwaysShowCalendars": true,
            locale: {
              format: 'DD/MM/YY',
              cancelLabel: 'Clear'
            }
        }, function(start, end, label) {
            party_change($('#party_list'));
        }).val("");
        
        $('#party-transaction-daterange').on('cancel.daterangepicker', function(ev, picker) {
          $('#party-transaction-daterange').val('');
        });
        
        //Refferal transaction date range filter
        $('#ref-transaction-daterange, input[name="ref-daterange"]').daterangepicker({
            "startDate": "02/01/2025",
            "endDate": moment(),
            ranges: {
                'Today': [moment(), moment()],
                'Yesterday': [moment().subtract(1, 'days'), moment().subtract(1, 'days')],
                'Last 7 Days': [moment().subtract(6, 'days'), moment()],
                'Last 30 Days': [moment().subtract(29, 'days'), moment()],
                'This Month': [moment().startOf('month'), moment().endOf('month')],
                'Last Month': [moment().subtract(1, 'month').startOf('month'), moment().subtract(1, 'month').endOf('month')]
            },
            "linkedCalendars": false,
            "autoUpdateInput": true,
            "alwaysShowCalendars": true,
            locale: {
              format: 'DD/MM/YY',
              cancelLabel: 'Clear'
            }
        }, function(start, end, label) {
            ref_change($('#ref_list'));
        //   console.log(start.format('YYYY-MM-DD') + ' to ' + end.format('YYYY-MM-DD'));
        }).val("");
        
        $('#ref-transaction-daterange').on('cancel.daterangepicker', function(ev, picker) {
          $('#ref-transaction-daterange').val('');
        });

        $('.counter-count').each(function () {
            $(this).prop('Counter',0).animate({
                Counter: $(this).text()
            }, {
                duration: Number($(this).data('counter-duration')),
                easing: 'swing',
                step: function (now) {
                    $(this).text(Math.ceil(now));
                }
            });
        });
    });
        
    function party_change(element) {
        // console.log($(element));
        var party_id = $(element).val();
        var from = $('#party-transaction-daterange').data('daterangepicker').startDate.format("YYYY-MM-DD H:m:s");
        var to = $('#party-transaction-daterange').data('daterangepicker').endDate.format("YYYY-MM-DD H:m:s");
        console.log(from, to);
        $.ajax({
            type: "GET",
            url: "<?= base_url('partyFilter/');?>" + party_id + '/' + from + '/' + to,
            data: party_id,
            dataType: "JSON",
            contentType: false,
            processData: false,
            success: function(response) {
                if(response == null)
                {
                    $('#party_transaction').html('0');    
                }else{
                    $('#party_transaction').html(response);
                }
                $('#party-filtered-transaction').text('Revenue generated by selected party until now.');
            }
        });
    }
    
    function ref_change(element) {
        // console.log($(element));
        var ref_id = $(element).val();
        var from = $('#ref-transaction-daterange').data('daterangepicker').startDate.format("YYYY-MM-DD H:m:s");
        var to = $('#ref-transaction-daterange').data('daterangepicker').endDate.format("YYYY-MM-DD H:m:s");
        console.log(from, to);
        $.ajax({
            type: "GET",
            url: "<?= base_url('refFilter/');?>" + ref_id + '/' + from + '/' + to,
            data: ref_id,
            dataType: "JSON",
            contentType: false,
            processData: false,
            success: function(response) {
                if(response == null)
                {
                    $('#ref_transaction').html('0');    
                }else{
                    $('#ref_transaction').html(response);
                }
                $('#ref-filtered-transaction').text('Revenue generated by selected refference until now.');
                // console.log(response);
            }
        });
    }
</script>

<?= $this->endSection('js') ?>